#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXECUTABLE=${DIR}/../vendor/genesis-php/genesis/genesis

if [ ! -f ${EXECUTABLE} ]; then
    echo "Genesis library not found. Please install dependencies via: composer install"
    exit
fi

${EXECUTABLE} --working-dir ${DIR} "$@"